# Generated by Django 3.1.4 on 2020-12-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couleurs', '0004_auto_20201226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.IntegerField(),
        ),
    ]
